name = "region-worker-daniel"
main = "./dist-region/index.js"
compatibility_date = "2023-11-09"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "rsc-workshop-daniel"
database_id = "f2f3d1d0-e659-4daf-96e8-fd120c280e46" # REPLACE THIS WITH YOUR ID!
migrations_dir = "./migrations"
